name: Build Container

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: checkout
        uses: actions/checkout@v2

      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up QEMU for docker multiarch builds
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        run: make push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
